# Generated by Django 4.2.27 on 2026-02-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_duration_alter_movie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
