# Generated by Django 4.2.27 on 2026-02-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rating_is_verified_watchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchHistory',
        ),
    ]
